// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaigiukgvuwdqgjfhkyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhaWdpdWtndnV3ZHFnamZoa3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDE2MDUsImV4cCI6MjA1NjY3NzYwNX0.jiZZg02zLw4nWEd6kxjUnl2aQfVflfOgDeHQQ2KYHn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);